#! /usr/bin/env python

# System
import argparse

# ROS
import rospy

# Conversation engine
from conversation_engine import ConversationEngine


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('--robot', type=str, default="amigo")
    args = parser.parse_args(rospy.myargv()[1:])

    rospy.init_node("conversation_engine")

    rospy.loginfo("Starting conversation engine with robot {}".format(args.robot))
    conv_engine = ConversationEngine(args.robot)

    rospy.loginfo("Conversation engine started")
    rospy.spin()
